server:
  port: 9000
spring:
  application:
    name: lab-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://192.168.1.4:34521/shiro_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: mysql2Moppo123#
mybatis:
  type-aliases-package: cn.ntshare.laboratory.model.entity
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true